# Generated by Django 3.2 on 2022-09-03 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuildMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild_name', models.CharField(max_length=300)),
                ('account_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='MechanicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_id', models.CharField(max_length=100)),
                ('encounter_name', models.CharField(max_length=500)),
                ('mechanic_name', models.CharField(max_length=1000)),
                ('mechanic_description', models.CharField(max_length=1000)),
                ('time_info', models.FloatField()),
                ('actor', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_id', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=300)),
                ('character_name', models.CharField(max_length=300)),
                ('profession', models.CharField(max_length=300)),
                ('target_dps', models.FloatField()),
                ('total_cc', models.FloatField()),
                ('downstates', models.IntegerField()),
                ('died', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='RaidKillTimes',
            fields=[
                ('log_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('encounter_name', models.CharField(max_length=500)),
                ('qualifying_date', models.DateField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('kill_duration_seconds', models.FloatField()),
                ('success', models.BooleanField()),
                ('cm', models.BooleanField()),
                ('input_file', models.CharField(max_length=1000)),
                ('link_to_upload', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.AddConstraint(
            model_name='guildmembers',
            constraint=models.UniqueConstraint(fields=('guild_name', 'account_name'), name='unique_active_guildmembers'),
        ),
    ]
