# Generated by Django 3.2 on 2022-09-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elite_insider_api', '0002_remove_playerinfo_died'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerinfo',
            name='died',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
