# Generated by Django 3.2 on 2022-09-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elite_insider_api', '0004_auto_20220925_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raidkilltimes',
            name='link_to_upload',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
