# Generated by Django 3.2 on 2022-10-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elite_insider_api', '0005_alter_raidkilltimes_link_to_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaidEncounters',
            fields=[
                ('encounter_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('arc_folder_name', models.CharField(max_length=200)),
                ('has_cm', models.BooleanField()),
                ('raid_wing', models.IntegerField()),
                ('boss_position', models.IntegerField()),
                ('relevant_boss', models.BooleanField()),
                ('wing_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'raid_encounters',
            },
        ),
    ]
