# Generated by Django 3.2 on 2022-10-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elite_insider_api', '0006_raidencounters'),
    ]

    operations = [
        migrations.AddField(
            model_name='raidkilltimes',
            name='uploaded_by',
            field=models.CharField(default='admin', max_length=500),
        ),
        migrations.AlterField(
            model_name='raidkilltimes',
            name='link_to_upload',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
